// |              Generated by SantoCAD                |
// |  Donatello Santoro (donatello.santoro@gmail.com)  |
// |  Michele Santomauro (michelesantomauro@gmail.com) |
// |                                                   |
// |  http://code.google.com/p/santocad/               |

// Colori
int getNumeroColori();
char* getNomeColore(int id);
void setColore(int idColore);


// Materiali
void setMaterialeBlackPlastic();
void setMaterialeBlackRubber();
void setMaterialeBrass();
void setMaterialeBronze();
void setMaterialeChrome();
void setMaterialeCopper();
void setMaterialeEmerald();
void setMaterialeGold();
void setMaterialeJade();
void setMaterialeObsidian();
void setMaterialePearl();
void setMaterialePewter();
void setMaterialePolishedBronze();
void setMaterialePolishedCopper();
void setMaterialePolishedGold();
void setMaterialePolishedSilver();
void setMaterialePuby();
void setMaterialePilver();
void setMaterialeTurquoise();
void setMaterialeWhitePlastic();
void setMaterialeDefault();
void setMateriale(int idMat);
int getNumeroMateriali();
char* getNomeMateriale(int id);