// |              Generated by SantoCAD                |
// |  Donatello Santoro (donatello.santoro@gmail.com)  |
// |  Michele Santomauro (michelesantomauro@gmail.com) |
// |                                                   |
// |  http://code.google.com/p/santocad/               |

#include <windows.h>
#include "GL/glew.h"
#include <GL/gl.h>
#include <GL/glut.h>
#include "cml/cml.h"
#include "materiali.h"

using namespace cml;

void controllaLimiti(vector3f *pos);
void disegnaSkybox(GLint idTextureSkymap, int posizioneY);
void disegnaPavimento(int tassellazione, bool wireframe);